# Generated by Django 4.2.30 on 2026-05-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente'), ('waiter', 'Mesero'), ('kitchen', 'Cocina'), ('cashier', 'Cajero')], default='waiter', max_length=20),
        ),
    ]
