# Generated by Django 4.2.30 on 2026-06-18 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Cocos Barrancos', max_length=80, verbose_name='Nombre del restaurant')),
                ('tagline', models.CharField(blank=True, default='Casa · Mar · Brasa', max_length=80, verbose_name='Lema')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business/', verbose_name='Logo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del negocio',
                'verbose_name_plural': 'Configuración del negocio',
            },
        ),
    ]
