# Generated by Django 4.2.30 on 2026-06-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='branch',
            field=models.CharField(blank=True, max_length=80, verbose_name='Sucursal'),
        ),
    ]
