# Generated by Django 4.2.30 on 2026-06-18 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Cocos Barrancos', max_length=80, verbose_name='Nombre del negocio')),
                ('tagline', models.CharField(blank=True, default='Casa · Mar · Brasa', max_length=80, verbose_name='Lema')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ticket/', verbose_name='Logo')),
                ('address', models.CharField(blank=True, max_length=160, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Teléfono')),
                ('tax_id', models.CharField(blank=True, max_length=40, verbose_name='RFC')),
                ('header_note', models.CharField(blank=True, max_length=120, verbose_name='Nota de encabezado')),
                ('footer_message', models.CharField(blank=True, default='¡Gracias por su visita!', max_length=160, verbose_name='Mensaje de pie')),
                ('accent_color', models.CharField(default='#C8553D', max_length=7, verbose_name='Color de acento')),
                ('paper_width', models.CharField(choices=[('58', '58 mm (angosto)'), ('80', '80 mm (estándar)')], default='80', max_length=2, verbose_name='Ancho de papel')),
                ('show_logo', models.BooleanField(default=True, verbose_name='Mostrar logo')),
                ('show_address', models.BooleanField(default=True, verbose_name='Mostrar dirección')),
                ('show_phone', models.BooleanField(default=True, verbose_name='Mostrar teléfono')),
                ('show_tax_id', models.BooleanField(default=False, verbose_name='Mostrar RFC')),
                ('show_table', models.BooleanField(default=True, verbose_name='Mostrar mesa')),
                ('show_cashier', models.BooleanField(default=True, verbose_name='Mostrar cajero')),
                ('show_datetime', models.BooleanField(default=True, verbose_name='Mostrar fecha y hora')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del ticket',
                'verbose_name_plural': 'Configuración del ticket',
            },
        ),
    ]
