# Generated by Django 4.2.30 on 2026-06-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsettings',
            name='billing_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='URL de facturación'),
        ),
        migrations.AddField(
            model_name='ticketsettings',
            name='show_qr',
            field=models.BooleanField(default=True, verbose_name='Mostrar QR de facturación'),
        ),
    ]
