# Generated by Django 4.2.30 on 2026-09-11 20:23

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_discount_by_order_discount_reason_and_more'),
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('counted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conteo de inventario',
                'verbose_name_plural': 'Conteos de inventario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('item_type', models.CharField(choices=[('ingredient', 'Insumo'), ('sellable_unit', 'Producto unitario')], default='ingredient', max_length=20, verbose_name='Tipo')),
                ('unit', models.CharField(choices=[('pza', 'Pieza'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('L', 'Litro'), ('ml', 'Mililitro'), ('caja', 'Caja'), ('otro', 'Otro')], default='pza', max_length=10, verbose_name='Unidad')),
                ('qty_on_hand', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='Existencia')),
                ('par_level', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Nivel deseado en almacén. Si la existencia baja de esto, aparece en Para comprar.', max_digits=12, verbose_name='Mínimo (par)')),
                ('reorder_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Si es > 0, se usa como mínimo sugerido al comprar; si no, se sugiere par − existencia.', max_digits=12, verbose_name='Cantidad de reorden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_item', to='menu.menuitem', verbose_name='Platillo vinculado (1:1)')),
            ],
            options={
                'verbose_name': 'Ítem de inventario',
                'verbose_name_plural': 'Ítems de inventario',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('purchase', 'Compra / entrada'), ('sale_deduct', 'Venta (descuento)'), ('count_adjust', 'Ajuste por conteo'), ('waste', 'Merma'), ('manual', 'Ajuste manual')], max_length=20)),
                ('quantity_delta', models.DecimalField(decimal_places=3, help_text='Positivo = entrada; negativo = salida.', max_digits=12)),
                ('qty_before', models.DecimalField(decimal_places=3, max_digits=12)),
                ('qty_after', models.DecimalField(decimal_places=3, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.order')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockitem')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_system', models.DecimalField(decimal_places=3, max_digits=12)),
                ('qty_counted', models.DecimalField(decimal_places=3, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcount')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_lines', to='inventory.stockitem')),
            ],
            options={
                'verbose_name': 'Línea de conteo',
                'verbose_name_plural': 'Líneas de conteo',
                'unique_together': {('count', 'stock_item')},
            },
        ),
        migrations.CreateModel(
            name='RecipeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Cantidad por platillo')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_lines', to='menu.menuitem')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_lines', to='inventory.stockitem')),
            ],
            options={
                'verbose_name': 'Línea de receta',
                'verbose_name_plural': 'Líneas de receta',
                'ordering': ['menu_item__name', 'stock_item__name'],
                'unique_together': {('menu_item', 'stock_item')},
            },
        ),
    ]
